const IS_GUEST_ENTER = 'IS_GUEST_ENTER',
			CHANGE_COUNTER = 'CHANGE_COUNTER',
			CHANGE_TEXT = 'CHANGE_TEXT',
			AUTH = 'AUTH',
			IS_USER_LOGIN = 'IS_USER_LOGIN',
			GET_PHOTOS_REQUEST = 'GET_PHOTOS_REQUEST',
			GET_PHOTOS_SUCCESS = 'GET_PHOTOS_SUCCESS';


export
	{
		IS_GUEST_ENTER,
		IS_USER_LOGIN,
		CHANGE_TEXT,
		CHANGE_COUNTER,
		AUTH,
		GET_PHOTOS_SUCCESS,
		GET_PHOTOS_REQUEST,
	}